config/routes.rb
InventorySystem::Application.routes.draw do
  resources :inventories
  root 'inventories#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  helper_method :inventories

  def index
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      redirect_to inventory_path(@inventory),
        notice: 'Inventory item successfully added'
    else
      render :new
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:title, :description, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/_form.html.erb
<%= simple_form_for(inventory) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :quantity %>
  <%= f.submit 'Add Inventory Item' %>
<% end %>

app/views/inventories/index.html.erb
<h1>Inventory Listing</h1>

<%= link_to 'Add Inventory Item', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>Add Inventory</h1>

<%= render 'inventories/form', inventory: @inventory %>

app/views/inventories/show.html.erb
<h1>Inventory Item Details</h1>
  <%= @inventory.title %><br />
  <%= @inventory.description %><br />
  <%= @inventory.quantity %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= flash[:notice] %></p>
<%= yield %>

</body>
</html>